import type { NextPage } from 'next'
import Head from 'next/head'
import { useRef } from 'react'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
    const iconsArray = useRef([...Array(70)].map(() => Math.random()))

    return (
        <div className={styles.container}>
            <Head>
                <title>CONGRATULATIONS🎉🥳🎊</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            {iconsArray.current.map((num, index) => {
                const icons = ['🎉', '🥳', '🎊']
                return (
                    <div className={styles.icon} key={index}>
                        {icons[Math.floor(num * icons.length)]}
                    </div>
                )
            })}
            <div className={styles.centered}>
                <div className={styles.box}>0</div>:
                <div className={styles.box}>0</div>:
                <div className={styles.box}>0</div>:
                <div className={styles.box}>0</div>
            </div>
        </div>
    )
}

export default Home
